### ISSUE TITLE
Dishonored 2 - Heavy artifacting once the main menu is reached

### ISSUE THREAD

**Issue by dennis1248** [daniel-schuermann/mesa#43]
Dishonored 2 causes heavy artificating once it reaches the main menu. The artifacting consists of a grid pattern of various colors spanning the entire screen, I attempted to take a screenshot but ended up with an empty image.  Quitting the game does not solve the issue, a full system restart is required.

If you would like to have system or Xorg logs just tell me which one you want and where to find them.

GPU is a Vega 64.

**Comment by daniel-schuermann** [comment]
Thanks for reporting! Something very helpful would be a renderdoc capture of the frame. Open renderdoc with ACO and start steam with ENABLE_VULKAN_RENDERDOC_CAPTURE=1, then you should be able to capture a frame which gets stored to /tmp/renderdoc/. If this doesn't work, you can also try to get that capture with LLVM enabled.

**Comment by dennis1248** [comment]
I am unable to take a Renderdoc capture because this bug makes the entire GUI unusable. I have to switch to another TTY and restart the system.

**Comment by daniel-schuermann** [comment]
Would you be able to take the capture with RADV_PERFTEST=llvm ?

**Comment by dennis1248** [comment]
The rendering/crash issue isn't present with RADV_PERFTEST=llvm. 

The game also doesn't launch when trying to start it through Steam+Renderdoc. So that is another obstacle preventing me from making a capture.

**Comment by doitsujin** [comment]
I managed to grab a renderdoc capture of the menu. Replaying this causes a GPU hang with ACO (RX 480).
https://mega.nz/#!IbpiyQLC!o-xxn_Ua5XRJ69OhrHf2IxlkCEPnv-Z7PKM-U38fTNE

Note that Renderdoc will fail to open this if the driver doesn't expose the `shaderFloat64` and `shaderInt64` capabilities.

**Comment by pendingchaos** [comment]
Should be fixed with 5a385de6a3a48af66007e70abed533134c53c456 (master) and 703cc10e32cfd22ee6a94d74fa8169391f0ed91e (backend).

With that change, @doitsujin's capture no longer causes GPU faults and appears to render correctly.

**Comment by doitsujin** [comment]
Can confirm that the game works fine now, thanks.

**Comment by regulator-g** [comment]
Hi guys,
I have switched from Padoka to ACO now Dishonored 2 freezes at the 2nd loading screen..
I have tried RADV_PERFTEST=llvm and it still freezes?

basically it gets past the first loading screen, plays the intro clips then freezes at the second loading screen

Any ideas / need me to test anything?

Ubuntu 19.04 + RX570

**update reinstalled driver today and seems to be fixed**
