### ISSUE TITLE
After upgrade mesa to 5c607722, became hangs GPU when I start Totem player

### ISSUE THREAD

**Issue by NTMan** [daniel-schuermann/mesa#97]
**Describe the bug:**
After upgrade mesa to 5c607722 commit, became hangs GPU when I start Totem player
Reproduced only in Wayland session.

**Steps for reproducing:**
1. Open Nautilus
2. Find some video file
3. Open video in totem

After third step, DE stops respond and in kernel log appears follow records:

```
[   92.843181] gmc_v9_0_process_interrupt: 2 callbacks suppressed
[   92.843196] amdgpu 0000:0b:00.0: [gfxhub] retry page fault (src_id:0 ring:0 vmid:3 pasid:32769, for process gnome-shell pid 1989 thread gnome-shel:cs0 pid 2035)
[   92.843216] amdgpu 0000:0b:00.0:   in page starting at address 0x0000000109f89000 from 27
[   92.843220] amdgpu 0000:0b:00.0: VM_L2_PROTECTION_FAULT_STATUS:0x00301031
[   92.843227] amdgpu 0000:0b:00.0: [gfxhub] retry page fault (src_id:0 ring:0 vmid:3 pasid:32769, for process gnome-shell pid 1989 thread gnome-shel:cs0 pid 2035)
[   92.843230] amdgpu 0000:0b:00.0:   in page starting at address 0x0000000109f8c000 from 27
[   92.843234] amdgpu 0000:0b:00.0: VM_L2_PROTECTION_FAULT_STATUS:0x00301031
[   92.843240] amdgpu 0000:0b:00.0: [gfxhub] retry page fault (src_id:0 ring:0 vmid:3 pasid:32769, for process gnome-shell pid 1989 thread gnome-shel:cs0 pid 2035)
[   92.843243] amdgpu 0000:0b:00.0:   in page starting at address 0x0000000109f8d000 from 27
[   92.843246] amdgpu 0000:0b:00.0: VM_L2_PROTECTION_FAULT_STATUS:0x00301031
[   92.843252] amdgpu 0000:0b:00.0: [gfxhub] retry page fault (src_id:0 ring:0 vmid:3 pasid:32769, for process gnome-shell pid 1989 thread gnome-shel:cs0 pid 2035)
[   92.843255] amdgpu 0000:0b:00.0:   in page starting at address 0x0000000109f85000 from 27
[   92.843258] amdgpu 0000:0b:00.0: VM_L2_PROTECTION_FAULT_STATUS:0x00301031
[   92.843264] amdgpu 0000:0b:00.0: [gfxhub] retry page fault (src_id:0 ring:0 vmid:3 pasid:32769, for process gnome-shell pid 1989 thread gnome-shel:cs0 pid 2035)
[   92.843267] amdgpu 0000:0b:00.0:   in page starting at address 0x0000000109f8b000 from 27
[   92.843270] amdgpu 0000:0b:00.0: VM_L2_PROTECTION_FAULT_STATUS:0x00301031
[   92.843276] amdgpu 0000:0b:00.0: [gfxhub] retry page fault (src_id:0 ring:0 vmid:3 pasid:32769, for process gnome-shell pid 1989 thread gnome-shel:cs0 pid 2035)
[   92.843279] amdgpu 0000:0b:00.0:   in page starting at address 0x0000000109f84000 from 27
[   92.843281] amdgpu 0000:0b:00.0: VM_L2_PROTECTION_FAULT_STATUS:0x00301031
[   92.843287] amdgpu 0000:0b:00.0: [gfxhub] retry page fault (src_id:0 ring:0 vmid:3 pasid:32769, for process gnome-shell pid 1989 thread gnome-shel:cs0 pid 2035)
[   92.843290] amdgpu 0000:0b:00.0:   in page starting at address 0x0000000109f8a000 from 27
[   92.843293] amdgpu 0000:0b:00.0: VM_L2_PROTECTION_FAULT_STATUS:0x00301031
[   92.843299] amdgpu 0000:0b:00.0: [gfxhub] retry page fault (src_id:0 ring:0 vmid:3 pasid:32769, for process gnome-shell pid 1989 thread gnome-shel:cs0 pid 2035)
[   92.843302] amdgpu 0000:0b:00.0:   in page starting at address 0x0000000109f83000 from 27
[   92.843304] amdgpu 0000:0b:00.0: VM_L2_PROTECTION_FAULT_STATUS:0x00301031
[   92.843310] amdgpu 0000:0b:00.0: [gfxhub] retry page fault (src_id:0 ring:0 vmid:3 pasid:32769, for process gnome-shell pid 1989 thread gnome-shel:cs0 pid 2035)
[   92.843313] amdgpu 0000:0b:00.0:   in page starting at address 0x0000000109f8e000 from 27
[   92.843316] amdgpu 0000:0b:00.0: VM_L2_PROTECTION_FAULT_STATUS:0x00301031
[   92.843322] amdgpu 0000:0b:00.0: [gfxhub] retry page fault (src_id:0 ring:0 vmid:3 pasid:32769, for process gnome-shell pid 1989 thread gnome-shel:cs0 pid 2035)
[   92.843325] amdgpu 0000:0b:00.0:   in page starting at address 0x0000000109f88000 from 27
[   92.843328] amdgpu 0000:0b:00.0: VM_L2_PROTECTION_FAULT_STATUS:0x00301031
[   97.844463] gmc_v9_0_process_interrupt: 38562 callbacks suppressed
[   97.844470] amdgpu 0000:0b:00.0: [gfxhub] retry page fault (src_id:0 ring:0 vmid:3 pasid:32769, for process gnome-shell pid 1989 thread gnome-shel:cs0 pid 2035)
[   97.844477] amdgpu 0000:0b:00.0:   in page starting at address 0x0000000109f8c000 from 27
[   97.844480] amdgpu 0000:0b:00.0: VM_L2_PROTECTION_FAULT_STATUS:0x00301031
[   97.844529] amdgpu 0000:0b:00.0: [gfxhub] retry page fault (src_id:0 ring:0 vmid:3 pasid:32769, for process gnome-shell pid 1989 thread gnome-shel:cs0 pid 2035)
[   97.844532] amdgpu 0000:0b:00.0:   in page starting at address 0x0000000109f87000 from 27
[   97.844535] amdgpu 0000:0b:00.0: VM_L2_PROTECTION_FAULT_STATUS:0x00301031
[   97.844569] amdgpu 0000:0b:00.0: [gfxhub] retry page fault (src_id:0 ring:0 vmid:3 pasid:32769, for process gnome-shell pid 1989 thread gnome-shel:cs0 pid 2035)
[   97.844572] amdgpu 0000:0b:00.0:   in page starting at address 0x0000000109f84000 from 27
[   97.844574] amdgpu 0000:0b:00.0: VM_L2_PROTECTION_FAULT_STATUS:0x00301031
[   97.844604] amdgpu 0000:0b:00.0: [gfxhub] retry page fault (src_id:0 ring:0 vmid:3 pasid:32769, for process gnome-shell pid 1989 thread gnome-shel:cs0 pid 2035)
[   97.844607] amdgpu 0000:0b:00.0:   in page starting at address 0x0000000109f8d000 from 27
[   97.844610] amdgpu 0000:0b:00.0: VM_L2_PROTECTION_FAULT_STATUS:0x00301031
[   97.845119] amdgpu 0000:0b:00.0: [gfxhub] retry page fault (src_id:0 ring:0 vmid:3 pasid:32769, for process gnome-shell pid 1989 thread gnome-shel:cs0 pid 2035)
[   97.845123] amdgpu 0000:0b:00.0:   in page starting at address 0x0000000109f8f000 from 27
[   97.845126] amdgpu 0000:0b:00.0: VM_L2_PROTECTION_FAULT_STATUS:0x00301031
[   97.845143] amdgpu 0000:0b:00.0: [gfxhub] retry page fault (src_id:0 ring:0 vmid:3 pasid:32769, for process gnome-shell pid 1989 thread gnome-shel:cs0 pid 2035)
[   97.845146] amdgpu 0000:0b:00.0:   in page starting at address 0x0000000109f86000 from 27
[   97.845149] amdgpu 0000:0b:00.0: VM_L2_PROTECTION_FAULT_STATUS:0x00301031
[   97.845189] amdgpu 0000:0b:00.0: [gfxhub] retry page fault (src_id:0 ring:0 vmid:3 pasid:32769, for process gnome-shell pid 1989 thread gnome-shel:cs0 pid 2035)
[   97.845192] amdgpu 0000:0b:00.0:   in page starting at address 0x0000000109f89000 from 27
[   97.845194] amdgpu 0000:0b:00.0: VM_L2_PROTECTION_FAULT_STATUS:0x00301031
[   97.845659] amdgpu 0000:0b:00.0: [gfxhub] retry page fault (src_id:0 ring:0 vmid:3 pasid:32769, for process gnome-shell pid 1989 thread gnome-shel:cs0 pid 2035)
[   97.845662] amdgpu 0000:0b:00.0:   in page starting at address 0x0000000109f8a000 from 27
[   97.845665] amdgpu 0000:0b:00.0: VM_L2_PROTECTION_FAULT_STATUS:0x00301031
[   97.845698] amdgpu 0000:0b:00.0: [gfxhub] retry page fault (src_id:0 ring:0 vmid:3 pasid:32769, for process gnome-shell pid 1989 thread gnome-shel:cs0 pid 2035)
[   97.845701] amdgpu 0000:0b:00.0:   in page starting at address 0x0000000109f8e000 from 27
[   97.845703] amdgpu 0000:0b:00.0: VM_L2_PROTECTION_FAULT_STATUS:0x00301031
[   97.845733] amdgpu 0000:0b:00.0: [gfxhub] retry page fault (src_id:0 ring:0 vmid:3 pasid:32769, for process gnome-shell pid 1989 thread gnome-shel:cs0 pid 2035)
[   97.845736] amdgpu 0000:0b:00.0:   in page starting at address 0x0000000109f82000 from 27
[   97.845739] amdgpu 0000:0b:00.0: VM_L2_PROTECTION_FAULT_STATUS:0x00301031
[   98.058540] [drm:amdgpu_dm_atomic_commit_tail [amdgpu]] *ERROR* Waiting for fences timed out or interrupted!
[  102.845621] gmc_v9_0_process_interrupt: 38549 callbacks suppressed
[  102.845628] amdgpu 0000:0b:00.0: [gfxhub] retry page fault (src_id:0 ring:0 vmid:3 pasid:32769, for process gnome-shell pid 1989 thread gnome-shel:cs0 pid 2035)
[  102.845640] amdgpu 0000:0b:00.0:   in page starting at address 0x0000000109f89000 from 27
[  102.845644] amdgpu 0000:0b:00.0: VM_L2_PROTECTION_FAULT_STATUS:0x00301031
[  102.845661] amdgpu 0000:0b:00.0: [gfxhub] retry page fault (src_id:0 ring:0 vmid:3 pasid:32769, for process gnome-shell pid 1989 thread gnome-shel:cs0 pid 2035)
[  102.845666] amdgpu 0000:0b:00.0:   in page starting at address 0x0000000109f86000 from 27
[  102.845669] amdgpu 0000:0b:00.0: VM_L2_PROTECTION_FAULT_STATUS:0x00301031
[  102.845687] amdgpu 0000:0b:00.0: [gfxhub] retry page fault (src_id:0 ring:0 vmid:3 pasid:32769, for process gnome-shell pid 1989 thread gnome-shel:cs0 pid 2035)
[  102.845691] amdgpu 0000:0b:00.0:   in page starting at address 0x0000000109f8a000 from 27
[  102.845694] amdgpu 0000:0b:00.0: VM_L2_PROTECTION_FAULT_STATUS:0x00301031
[  102.845703] amdgpu 0000:0b:00.0: [gfxhub] retry page fault (src_id:0 ring:0 vmid:3 pasid:32769, for process gnome-shell pid 1989 thread gnome-shel:cs0 pid 2035)
[  102.845707] amdgpu 0000:0b:00.0:   in page starting at address 0x0000000109f88000 from 27
[  102.845711] amdgpu 0000:0b:00.0: VM_L2_PROTECTION_FAULT_STATUS:0x00301031
[  102.845802] amdgpu 0000:0b:00.0: [gfxhub] retry page fault (src_id:0 ring:0 vmid:3 pasid:32769, for process gnome-shell pid 1989 thread gnome-shel:cs0 pid 2035)
[  102.845807] amdgpu 0000:0b:00.0:   in page starting at address 0x0000000109f80000 from 27
[  102.845810] amdgpu 0000:0b:00.0: VM_L2_PROTECTION_FAULT_STATUS:0x00301031
[  102.846195] amdgpu 0000:0b:00.0: [gfxhub] retry page fault (src_id:0 ring:0 vmid:3 pasid:32769, for process gnome-shell pid 1989 thread gnome-shel:cs0 pid 2035)
[  102.846199] amdgpu 0000:0b:00.0:   in page starting at address 0x0000000109f8c000 from 27
[  102.846202] amdgpu 0000:0b:00.0: VM_L2_PROTECTION_FAULT_STATUS:0x00301031
[  102.846219] amdgpu 0000:0b:00.0: [gfxhub] retry page fault (src_id:0 ring:0 vmid:3 pasid:32769, for process gnome-shell pid 1989 thread gnome-shel:cs0 pid 2035)
[  102.846222] amdgpu 0000:0b:00.0:   in page starting at address 0x0000000109f84000 from 27
[  102.846226] amdgpu 0000:0b:00.0: VM_L2_PROTECTION_FAULT_STATUS:0x00301031
[  102.846276] amdgpu 0000:0b:00.0: [gfxhub] retry page fault (src_id:0 ring:0 vmid:3 pasid:32769, for process gnome-shell pid 1989 thread gnome-shel:cs0 pid 2035)
[  102.846280] amdgpu 0000:0b:00.0:   in page starting at address 0x0000000109f8e000 from 27
[  102.846284] amdgpu 0000:0b:00.0: VM_L2_PROTECTION_FAULT_STATUS:0x00301031
[  102.846332] amdgpu 0000:0b:00.0: [gfxhub] retry page fault (src_id:0 ring:0 vmid:3 pasid:32769, for process gnome-shell pid 1989 thread gnome-shel:cs0 pid 2035)
[  102.846336] amdgpu 0000:0b:00.0:   in page starting at address 0x0000000109f87000 from 27
[  102.846340] amdgpu 0000:0b:00.0: VM_L2_PROTECTION_FAULT_STATUS:0x00301031
[  102.846363] amdgpu 0000:0b:00.0: [gfxhub] retry page fault (src_id:0 ring:0 vmid:3 pasid:32769, for process gnome-shell pid 1989 thread gnome-shel:cs0 pid 2035)
[  102.846366] amdgpu 0000:0b:00.0:   in page starting at address 0x0000000109f82000 from 27
[  102.846370] amdgpu 0000:0b:00.0: VM_L2_PROTECTION_FAULT_STATUS:0x00301031
[  103.189003] [drm:amdgpu_job_timedout [amdgpu]] *ERROR* ring gfx timeout, signaled seq=1065, emitted seq=1067
[  103.189070] [drm:amdgpu_job_timedout [amdgpu]] *ERROR* Process information: process gnome-shell pid 1989 thread gnome-shel:cs0 pid 2035
[  103.189074] amdgpu 0000:0b:00.0: GPU reset begin!
[  104.031007] amdgpu 0000:0b:00.0: [drm:amdgpu_ring_test_helper [amdgpu]] *ERROR* ring kiq_2.1.0 test failed (-110)
[  104.031181] [drm:gfx_v9_0_hw_fini [amdgpu]] *ERROR* KCQ disable failed
[  104.052555] amdgpu 0000:0b:00.0: GPU mode1 reset
[  104.554716] [drm] psp mode1 reset succeed 
[  104.640948] amdgpu 0000:0b:00.0: GPU reset succeeded, trying to resume
```

**System information:**
 - GPU: AMD Radeon VII
 - ACO version: 5c607722

Last working mesa for me is 9bdc04c3

[dmesg-mesa-5c607722.txt](https://github.com/daniel-schuermann/mesa/files/3458545/dmesg-mesa-5c607722.txt)

**Comment by daniel-schuermann** [comment]
Thx for reporting! Does this issue disappear if you switch back to some older mesa? Could you start totem with RADV_PERFTEST=llvm and see if the issue goes away? I didn't know that totem uses vulkan in any way, but if it uses mesa, maybe it gets fixed with the next rebase..

**Comment by NTMan** [comment]
With `RADV_PERFTEST=llvm` or not it does not matter because something happens inside DE, because if I upgrade mesa from 9bdc04c3 to 5c607722 without re-login the nothing is happening. This issue appears after re-login.

And honestly, I did not make bisect the code. When ran into this issue I just downgraded mesa several times until this issue disappears.

In this repo https://copr.fedorainfracloud.org/coprs/xxmitsu/mesa-aco/builds/ packages builded from commits 9bdc04c3 and 5c607722 are adjacent.

I suppose that in commit 5c607722 was merged some changes from the mesa which are broke playing video functionality in Totem.

**Comment by vulturm** [comment]
You can try official mesa-git with distro llvm at
https://copr.fedorainfracloud.org/coprs/xxmitsu/mesa-git/

or mesa-git and llvm-git
https://copr.fedorainfracloud.org/coprs/xxmitsu/mesa-and-llvm-git/ and see
if you can indentify the culprit.

**Comment by Venemo** [comment]
Are you sure this is an ACO problem? Do you have gstreamer-vaapi or some other 'bad' gstreamer plugin installed?

**Comment by NTMan** [comment]
> You can try official mesa-git with distro llvm at https://copr.fedorainfracloud.org/coprs/xxmitsu/mesa-git/

Thanks, I checked the official mesa-git repo and did not see that the described issue is reproduced there.

So there is every reason to assume that the problem in aco patches.

I also tried bisection mesa-aco, but unable to select the good commit because of error message `fatal: Needed a single revision`.
I don't understand what it means.
I would glad if anybody could help me with bisecting.

```
$ git bisect start
$ git bisect good 9bdc04c3
fatal: Needed a single revision
Bad rev input: 9bdc04c3
```

**Comment by Venemo** [comment]
@NTMan the error message you got means that git doesn't recognize the revision that you gave it. Otherwise you are doing it right.

```
git bisect start
git bisect good <last known good commit>
git bisect bad HEAD # assuming that the current HEAD is bad
```

**Comment by NTMan** [comment]
It is weird because GitHub can show commit `https://github.com/daniel-schuermann/mesa/commit/9bdc04c3811c8d295c942986830a3351067d4d55`, but local git couldn't recognize this revision.

```
$ git bisect good 9bdc04c3811c8d295c942986830a3351067d4d55
fatal: Needed a single revision
Bad rev input: 9bdc04c3811c8d295c942986830a3351067d4d55
```

I am never seen such a problem before.

**Comment by miscco** [comment]
That is indeed strange. It could be that you did not fetch the revision in you local repository?

**Comment by pendingchaos** [comment]
You probably don't have the good commit because it's not in the master branch (or any branch, according to github). This is because we rebase ACO on a newer Mesa about every week.

That package (xxmitsu's mesa-git) seems to be a more recent Mesa version than what ACO is currently based on. It's possible that the issue was fixed but ACO isn't based on a version of Mesa that includes the fix.

You could try using 08f1cefecd84f851da6d90200bd7af0ecf5bf855 (the Mesa version ACO is currently based on) and if it works, then the problem is probably caused by ACO. If it doesn't work, then it's probably unrelated.

Also, I'm not sure how effective a bisect would be. The good commit (9bdc04c3) and the bad commit (5c60772) are on different branches. You could use e03f3db9c4794821fc2ad31c54fa27cc7158f073 as the good commit (which is on the same branch as 5c60772), but that commit probably won't actually work if the issue is unrelated to ACO.

**Comment by vulturm** [comment]
@NTman, just for curiosity sake, could you try mesa-aco with latest
drm-next kernel ?
https://copr.fedorainfracloud.org/coprs/xxmitsu/kernel-amdgpu-next/ ? you
also have instructions to revert it back to distro official one after the
testing.

**Comment by junglerobba** [comment]
I have the same issue on Sway with applications like Firefox, mpv and qutebrowser and I'm fairly certain it's an upstream mesa issue that's already fixed in master. If I did my testing correctly it was introduced in f8b6c5a1a638e465d7c536a1204536175aeaf20f, but I couldn't find the commit that fixed it, except that it no longer happens on latest master.

**Comment by NTMan** [comment]
> You could try using [08f1cef](https://github.com/daniel-schuermann/mesa/commit/08f1cefecd84f851da6d90200bd7af0ecf5bf855) (the Mesa version ACO is currently based on) and if it works, then the problem is probably caused by ACO. If it doesn't work, then it's probably unrelated.

I built mesa-aco from this commit and the issue is still here.

> You could use [e03f3db](https://github.com/daniel-schuermann/mesa/commit/e03f3db9c4794821fc2ad31c54fa27cc7158f073) as the good commit (which is on the same branch as [5c60772](https://github.com/daniel-schuermann/mesa/commit/5c6077221dd0718f09c12fc1b1a6f65595416288)), but that commit probably won't actually work if the issue is unrelated to ACO.

And on this commit, the issue is still here.

So as you said before I suppose to needed wait mesa-aco based on newer version mesa and cross fingers for luck. When do you plan rebase ACO on a newer Mesa?

> @NTMan, just for curiosity sake, could you try mesa-aco with latest drm-next kernel ? https://copr.fedorainfracloud.org/coprs/xxmitsu/kernel-amdgpu-next/ ? you also have instructions to revert it back to distro official one after the testing.

We did not expect a miracle from the new kernel. And the miracle did not happen.
Only error messages in kernel log became a bit more verbose:
```
[   89.294886] gmc_v9_0_process_interrupt: 49 callbacks suppressed
[   89.294891] amdgpu 0000:0b:00.0: [gfxhub0] retry page fault (src_id:0 ring:0 vmid:3 pasid:32769, for process gnome-shell pid 1993 thread gnome-shel:cs0 pid 2030)
[   89.294894] amdgpu 0000:0b:00.0:   in page starting at address 0x000000010a787000 from client 27
[   89.294896] amdgpu 0000:0b:00.0: VM_L2_PROTECTION_FAULT_STATUS:0x00301031
[   89.294897] amdgpu 0000:0b:00.0: 	 MORE_FAULTS: 0x1
[   89.294898] amdgpu 0000:0b:00.0: 	 WALKER_ERROR: 0x0
[   89.294899] amdgpu 0000:0b:00.0: 	 PERMISSION_FAULTS: 0x3
[   89.294900] amdgpu 0000:0b:00.0: 	 MAPPING_ERROR: 0x0
[   89.294905] amdgpu 0000:0b:00.0: [gfxhub0] retry page fault (src_id:0 ring:0 vmid:3 pasid:32769, for process gnome-shell pid 1993 thread gnome-shel:cs0 pid 2030)
[   89.294906] amdgpu 0000:0b:00.0:   in page starting at address 0x000000010a784000 from client 27
[   89.294907] amdgpu 0000:0b:00.0: VM_L2_PROTECTION_FAULT_STATUS:0x00301031
[   89.294908] amdgpu 0000:0b:00.0: 	 MORE_FAULTS: 0x1
[   89.294909] amdgpu 0000:0b:00.0: 	 WALKER_ERROR: 0x0
[   89.294910] amdgpu 0000:0b:00.0: 	 PERMISSION_FAULTS: 0x3
[   89.294911] amdgpu 0000:0b:00.0: 	 MAPPING_ERROR: 0x0
[   89.294915] amdgpu 0000:0b:00.0: [gfxhub0] retry page fault (src_id:0 ring:0 vmid:3 pasid:32769, for process gnome-shell pid 1993 thread gnome-shel:cs0 pid 2030)
[   89.294916] amdgpu 0000:0b:00.0:   in page starting at address 0x000000010a789000 from client 27
[   89.294917] amdgpu 0000:0b:00.0: VM_L2_PROTECTION_FAULT_STATUS:0x00301031
[   89.294918] amdgpu 0000:0b:00.0: 	 MORE_FAULTS: 0x1
[   89.294919] amdgpu 0000:0b:00.0: 	 WALKER_ERROR: 0x0
[   89.294920] amdgpu 0000:0b:00.0: 	 PERMISSION_FAULTS: 0x3
[   89.294921] amdgpu 0000:0b:00.0: 	 MAPPING_ERROR: 0x0
```
[dmesg111.txt](https://github.com/daniel-schuermann/mesa/files/3463689/dmesg111.txt)

**Comment by pendingchaos** [comment]
@NTMan: we've just rebased ACO on a very recent version of Mesa: 5254e53debe3bcfe3d8dc1ba4110fda8b6a616f9

**Comment by NTMan** [comment]
> @NTMan: we've just rebased ACO on a very recent version of Mesa: [5254e53](https://github.com/daniel-schuermann/mesa/commit/5254e53debe3bcfe3d8dc1ba4110fda8b6a616f9)

Thanks, I tested mesa-aco with commit 5254e53debe3bcfe3d8dc1ba4110fda8b6a616f9 and sees than issue was completely gone.
